### PR TITLE
Test CirrusCI env variables security through PR

### PR DESCRIPTION
**Pull request by abitrolly**

### CODE REVIEW

**Comment by abitrolly** [comment]
Cirrus CI is echo resistant.

image

**Comment by abitrolly** [comment]
env is stolen successfully, cleaning up the trace.

**Comment by fkorotkov** [comment]
@abitrolly you should try to push with a user that doesn't have write permissions to the repository. Users with read-only access like outside contributors won't be able to even use secret variables.

**Comment by abitrolly** [comment]
I see that it is even documented. I still sent a PR https://github.com/cirruslabs/cirrus-ci-docs/pull/358 to make it more clear. Maybe the next time I won't miss that. Thanks for the clarification.

**Pull request closed without merging**
